backend:
  name: github
  repo: Soulmatters/pwa-starter-kit # Path to your Github repository
  
media_folder: "src/content/images"
public_folder: "content/images"

collections: #A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI
    label_singular: "Blog post" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "src/data/_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "relation", collection: "user", searchFields: ["name", "id"], valueField: "id", displayFields: ["name"]}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "user" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "User" # Used in the UI
    label_singular: "User data" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "src/data/_users"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "Website", name: "website", widget: "string", tagname: "p"}
      - {label: "Email", name: "email", widget: "string", tagname: "p"}
      - {label: "id", name: "id", widget: "string", tagname: "p"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}

  - name: "tags" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Tags" # Used in the UI
    label_singular: "tag" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "src/_tags"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "id", name: "id", widget: "string", tagname: "p"}
  - name: "pagina" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pagină" # Used in the UI
    label_singular: "Pagină" # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "src/data/_pages"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
     